language: java
jdk:
  - oraclejdk9
install: true
addons:
  sonarcloud:
    organization: "alexbeuthhs-github" # the key of the org
script:
- mvn clean install test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
