language: java
jdk:
  - oraclejdk9
install: true
addons:
  sonarcloud:
    organization: "alexbeuthhs-github" # the key of the org you chose at step #3
script:
- mvn clean install test
- sonar-scanner
